### ISSUE TITLE
better inset

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#11]
Would it be possible to integrate this patch https://developer.blender.org/D1669 ? It's from the dev of the bevel modifier and add self intersection detection to the inset operator, which is much needed in architecture and precision modelling. It rocks.

**Comment by mauge123** [comment]
I'll contact the author ;)

Thanks!

**Comment by mauge123** [comment]
It was applied on 7af74ee9371577d854f64c8a3cb71f09e818073b

**Comment by mirlip** [comment]
If you want, I made some corrections to make it compile on VS2013:
http://www.pasteall.org/69758/diff
It's the full diff from BF-master, so you may have to revert the old one first.

**Comment by mauge123** [comment]
I can see the patch is using spaces for indentation, so it's hard to check changes if they are not replaced first. Blender uses tabs for indentation.

I also see you have changed inline for __inline, i see the first one is used in all other places in blender code ¿?

**Comment by mirlip** [comment]
Yes, only this __inline was important I think. For some reason, VS2013 doesn't like it in this case. Don't ask me why, it's MS :D

**Comment by mauge123** [comment]
b9d6a4a9cd8e407bb3b23ce4e9cc2d52e9a16da2 includes the fixes you proposed to get compiled sucssefully on MSVC.

**Comment by mirlip** [comment]
I'm glad it worked without breaking Linux compilation :)
