### ISSUE TITLE
modifiers crash

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#12]
Many modifiers which take another object as input (like boolean, shrinkwrap, etc...) crash with mechanical-blender.
To reproduce, duplicate default cube, add boolean on it and select other cube as object for the bool operation. Blender crashes.

**Comment by mauge123** [comment]
Being applied 392f2404f7f97a4ff339db0fe42050d79050d691 it does not crash a boolean op.
Any other issue with modifiers ?

**Comment by mirlip** [comment]
Fix works great for modifiers, but this file http://www.pasteall.org/blend/41530 still crashes when you do alt+C -> mesh on the selected curve.

**Comment by mirlip** [comment]
fixed by latest commit
