### ISSUE TITLE
crash when rendering certain files

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#13]
https://download.blender.org/demo/test/splash-pokedstudio.blend.zip and https://download.blender.org/demo/test/Demo_274.zip (scene-Helicopter-27) crash when trying to render them with the mecha branch. 2.77a renders correctly.

**Comment by mauge123** [comment]
try with commit 392f2404f7f97a4ff339db0fe42050d79050d691 applied as was crashing for the same issue, although  i cannot render the splash but it's a memory issue as i'm not working on a computer suposed to consume large quantities of memory.

**Comment by mirlip** [comment]
it crashes with this commit, I'll try with latest commit.

**Comment by mirlip** [comment]
Latest commit solves all 3 problems, nice :)

**Comment by mauge123** [comment]
Thanks for your active collaboration!! ;)
