### ISSUE TITLE
IFC export

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#19]
Would it be possible to include IFCOpenShell to have IFC export from Blender?
http://ifcopenshell.org/
https://sourceforge.net/projects/ifcopenshell/
It already has an IFC importer and Python bindings for writing IFC files, but a proper exporter would be awesome.

**Comment by mauge123** [comment]
At the moment we are focusing to geometry.

Which will be the benefits of this exporter?

**Comment by mirlip** [comment]
It allows to communicate with other BIM-compatible softwares like Revit, Autocad, Allplan, etc... without loosing the construction informations. It's more for architects than for engineer. So I can understand if it doesn't interest you. Was just a suggestion :)

**Comment by mauge123** [comment]
;)
