### ISSUE TITLE
grab is too fast when using millimeters in perspective view

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#24]
Hi,
When using the grab tool near 0, it moves really good. But if you work in millimetre, and want to move an object that is on meter away from 0, it will start to make big jumps instead of smooth translations in perspective view (orthogonal works great). Would it be possible to make the grab movement constantly fast to make it possible to work in millimetres in perspective view?
Regards

**Comment by mauge123** [comment]
is this a mechanical blender issue or a blender issue ?

**Comment by mirlip** [comment]
It is a Blender issue, but I don't think it will be recognised as a bug but more as a limitation, like most of the things that have to do with precision at the moment. I guess the move steps are not linear in space. So it should only be a matter of making the object transform a linear equation of the mouse movement. Like object delta (Blender Unit) = mouse delta (Pixel). Ideal would be to make the object stay under the mouse cursor now that we have the free view during transform.

**Comment by mauge123** [comment]
Nops,  the issue was that the 3D point was calc projecting the mouse position on plane on 0,0,0.

We will not rewrite the transform code because is used in lots on places, and as was said,  big changes are resulting on a pain during merges.

should be fixed on e871ecc86d7da2b817625bd82acef18b7d9bc179

**Comment by mauge123** [comment]
Now the grab is controlled, but if the objects are far away, the translation is slowest, because there is a hard coded value, that should be adjusted.

**Comment by mirlip** [comment]
Just tested the patch. It works well, but I agree the speed should be relative to the object distance to viewpoint.

**Comment by mirlip** [comment]
Hi Mauge,

The bug also appear when scaling objects in edit mode ( far away from world origin). Object mode works great.

**Comment by mauge123** [comment]
As the changes are inside transform code, affects to all transform. I solved it using a point at a fixed distance of the view origin, will be solved using a point based on selection

**Comment by mirlip** [comment]
The fix works great in object mode, but not in edit mode.

**Comment by mirlip** [comment]
Up, this is really a problem for precision modeling. Please solve it in edit mode also.

**Comment by mauge123** [comment]
Um.. works fine for me, so it may be solved on recent commits and not related.

**Comment by mirlip** [comment]
Hi, I just compiled the latest version and it's still there. If I put a cube at (3000, 3000, 3000) = 3m in all direction when working in mm and then go to edit mode and press S to scale (in perspective view), the cube becomes instantly extremely big. This doesn't happen in object mode thanks to the fix, it also doesn't happen in edit mode if in the orthogonal top view.

**Comment by mauge123** [comment]
It was not working in the case the object origin was far away from origin. Now should be fixed!

**Comment by mirlip** [comment]
Hi, thanks for the fix but after compiling with latest changes, the cube still becomes huge instantly when trying to scale in edit mode. You are right, it only happen when the origin of the object is "far" away from 0.

**Comment by mirlip** [comment]
Yes it works now, thank you :) Really great addition :)

**Comment by mauge123** [comment]
;)
