### ISSUE TITLE
crash in the input user preferences

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#28]
when trying to expand the "translate" action in "user prefs"-> "inputs" -> search for "trans" -> then in "3D View" -> click to expand "translate" -> it crashes with segfault under Linux at least.

Crash report:
[blender.crash.txt](https://github.com/mauge123/mechanical-blender/files/428730/blender.crash.txt)

**Comment by mauge123** [comment]
Thanks! ;)
