### ISSUE TITLE
allow multiple snap elements to be selected

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#29]
At the moment in Blender, you can only choose one element/target at once. It would be great to have an additive selection like for the selection in edit mode (selection can be set to vert and/or edge and/or face).

**Comment by mauge123** [comment]
I do not understand your proposal. Are you refererring to snap ?

**Comment by mirlip** [comment]
Yes, at the moment you can only snap to vert OR edge OR face Or ... and it would be much better like other app to be able to snap to vert AND edge AND face.
I just compared it to the edit mode selection, because it already has such a UI where you can select vert AND edge AND faces at the same time.

**Comment by mauge123** [comment]
This is already possible in mechanical blender usign the keyboard shortcut during the transform (because it's not modal) So you can (for example) start snapping to vert, select it, change to face (using CTRL+SHIFT+TAB) and placing the vertex on a face  ;)

**Comment by mirlip** [comment]
That's really nice if it's already possible, but a good UI is missing then. At least some info on what keys to press to get the choice. It would be good to have the same icon set as for selection near the snapping magnet for consistency.

**Comment by mauge123** [comment]
um... re-reading, What is possible at this moment is to change the setting (Vert, Edge, Face, and the added ones: Dims, References, geometry) during the operation.

**Comment by mirlip** [comment]
Ok, I found the geometry subpanel in the scene panel, it's exactly what I meant. It would be good to add face, edge and vert there.
