### ISSUE TITLE
blender crashes when launched

### ISSUE THREAD

**Issue by aslakstubsgaard** [mauge123/mechanical-blender#31]
I pulled a clone, ran cmake, make, and make install. Afterwards the blender binary in the resulting  /build/bin folder crashes when launched, given the following message:
```
Color management: using fallback mode for management
*** stack smashing detected ***: ./blender terminated
Aborted (core dumped)

```
any idears as to why this is the case?

btw I'm on Ubuntu 16.04 / 64bit

**Comment by mauge123** [comment]
I would like to have more info, the crash file created if created, and also which is is the cmake config.

**Comment by mauge123** [comment]
Would like to know if the issue is still remaining,or  if someone else is still with this issue.
