### ISSUE TITLE
middle point is not always found

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#36]
In this http://pasteall.org/blend/index.php?id=46042 blend file, the middle point which should be found where the 3D cursor is won't be snapped to for some reason. If you delete the upper right vertex, this point will be found by the snap system.

**Comment by mauge123** [comment]
this is because the edge is part of planar surface.  You can show up the found geometry on properties tab -> Mesh Display -> Show geometry

The algorithm ignores inner edges of a planar surface.

**Comment by mirlip** [comment]
Thanks for the explanation. Do you plan to add an exhaustive version to find all middle points? I mean as an option, so that user can choose between speed and quality.
