### ISSUE TITLE
only display dimensions in the current viewplane in orthoview.

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#4]
It may help readability to have an option to limit the display of dimensions to the dimensions being in the current view plane: only dimensions in the x,y plane when in top or bottom view, etc.... Maybe a threshold would help for dimensions that are not perfectly coplanar, but should still be displayed?

**Comment by mirlip** [comment]
I'll try to find which addon is causing the problem.

**Comment by mauge123** [comment]
I do not understand the relationship with addons and the issue

**Comment by mirlip** [comment]
Sorry, my bad, wrong thread :D

**Comment by mirlip** [comment]
What I mean is you don't want to see a building height when in the top view or a building depth when in front view. Even worse is when you have an array of measure on Z and you look on the top view, they all get written in one place making it unreadable. As they are not needed in those case, I would only draw dimensions which are really visible in the current view. Something similar to the 3D view translate manipulator (the red, green and blue arrows), the arrows fade slowly to become invisible when orthogonal to view. Would be perfect to replicate it for dimensions.

**Comment by mauge123** [comment]
I think that my first reply was not intended for your first message. I agree that this is a missing issue.

**Comment by mauge123** [comment]
The commit f51f2f8ee15639f92c77bd0058d14c55a70a8928 by allows to hide perpendicular dimensions to ortho view, a check is placed on display mesh tab, to enable/disable it. 57ab3734cd13bde652a40880ec6a8ed9b76adfef

**Comment by mirlip** [comment]
Awesome :) But I get following error while compiling:
`C:\Users\test\blender\blender\source\blender\editors\uvedit\uvedit_parametrizer.c(748): error C4013: 'finite' undefined; assuming extern returning int [C:\Users\test\blender\build_windows\source\blender\editors\uvedit\bf_editor_uvedit.vcxproj]`

**Comment by mirlip** [comment]
Nice work. It works great in edit mode, but get automatically disabled in object mode.
