### ISSUE TITLE
every git url in .gitmodules contains two colons instead of one

### ISSUE THREAD

**Issue by rakete** [mauge123/mechanical-blender#42]
I had the following problem:

    ~/b/mechanical-blender:master> git submodule update 
    Cloning into 'release/datafiles/locale'...
    fatal: Unable to find remote helper for 'git'
    fatal: clone of 'git:://git.blender.org/blender-translations.git' into submodule path 'release/datafiles/locale' failed

Which is caused by two colons in the git urls in .gitmodules. The urls look like this:

    git:://git.blender.org/blender-addons.git

but should look like this:

    git://git.blender.org/blender-addons.git

**Comment by mauge123** [comment]
Thanks ;)
