### ISSUE TITLE
Comment: Suggestions and more info?

### ISSUE THREAD

**Issue by LordStreetguru** [mauge123/mechanical-blender#45]
Tried to e-mail but it returned an error, figured I'd try here. Is the project still going?

Seems like Mechanical Blender is kind of what I'm looking for, every CAD program I've tried has been less intuitive and functional than TinkerCAD.

However you guys should really make just a simple .exe version so people can try it out, would also be useful to have a forum as well.

Maybe most importantly the home page of the site should have rolling video updates showing off how things are progressing, if it's functional enough you could even make a patreon or something to fund it.

My idea for a "Pipedream CAD" add on or fork of blender, would turn it into TinkerCAD basically, but with more precision, flexibility, and automation. Would suggest a photoshop like interface as well when it comes to layers/objects, and the main goal is just drawing by points, where the software would then generate the lines or plans, or shapes between those points, and when finished would generate an object within a given polygon count.

My focus is mostly on 3D printers though, so features like automatic mirroring of an object would be great as well, maybe even being able to split a finished object with automatic rejoining points like holes for pegs built in as well.

An example of the features/sequence I'm trying to illustrate/find.
Create Point A at (0,0,0)
Create Cube(6 sided polygon) FROM point A in X direction from point A (Auto generate points on each vertex of the Polygon)
Create point 50% between points A1/A4. A2/A3
Create HOLE Cylinder Object around New Point
To turn this into a dome with an easily adjustable roof, I could then
Clone Points A3/B3/A4/B4
Create half circle between New Points with Angle 45* (between A3/B4, A4,B3)

https://forum.level1techs.com/uploads/default/original/3X/3/3/33d1fede54693ba716b1e76fd79c9d885fe2aea9.jpeg

**Comment by mauge123** [comment]
Hi, issues with tmaq's hosting have been already addressed.

The project itself has been frezzen for some time, due to lack of resources and time for it on my part.

The scope of the project is adding CAD features, not changing the interface of blender. 

About binaries were waiting for a stable version to release them, altough some of them were already avaliable for testing.

Thanks for your interest!
