### ISSUE TITLE
can't build on VS2013

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#7]
Trying to build latest master give this:
`     Creating library C:/Users/test/git/build_windows_full/bin/Release/blenderplayer.lib and object C:/Users/test/git/build_windows_full/bin/Release/blenderplayer.exp
bf_blenkernel.lib(object_update.obj) : error LNK2019: unresolved external symbol get_dimension_mid referenced in function BKE_object_handle_data_update [C:\Users\test\git\build_windows_full\source\blenderplayer\blenderplayer.vcxproj]
bf_blenkernel.lib(object_update.obj) : error LNK2019: unresolved external symbol dimension_data_update referenced in function BKE_object_handle_data_update [C:\Users\test\git\build_windows_full\source\blenderplayer\blenderplayer.vcxproj]
bf_bmesh.lib(bmesh_core.obj) : error LNK2001: unresolved external symbol dimension_data_update [C:\Users\test\git\build_windows_full\source\blenderplayer\blenderplayer.vcxproj]
bf_bmesh.lib(bmesh_core.obj) : error LNK2019: unresolved external symbol mid_of_2_points referenced in function BM_dim_create [C:\Users\test\git\build_windows_full\source\blenderplayer\blenderplayer.vcxproj]
bf_bmesh.lib(bmesh_core.obj) : error LNK2019: unresolved external symbol center_of_3_points referenced in function BM_dim_create [C:\Users\test\git\build_windows_full\source\blenderplayer\blenderplayer.vcxproj]
C:\Users\test\git\build_windows_full\bin\Release\blenderplayer.exe : fatal error LNK1120: 4 unresolved externals [C:\Users\test\git\build_windows_full\source\blenderplayer\blenderplayer.vcxproj]
     Creating library C:/Users/test/git/build_windows_full/bin/Release/blender-app.lib and object C:/Users/test/git/build_windows_full/bin/Release/blender-app.exp
  blender.vcxproj -> C:\Users\test\git\build_windows_full\bin\Release\blender-app.exe
"Build Failed"`

**Comment by mirlip** [comment]
Thanks for the fix in latest master :)
The plane constraint is really good. But what is the axis constraint for? I see no difference with and without. The way we can change the dimension in one or both direction is really well thought. I would move the dimension position to the "display" part of N panel and change the text from "dimension:" to "position:" It would be awesome to be able to click on the number and directly edit it in the 3D view.

**Comment by mauge123** [comment]
The Axis constraint is used for diameter dimensions (radius is comming soon :P) .
It modifies all vertices that are at same distance (perp) to axis. So if you have a cilinder, with a diameter dimension in one side, you modify all cilinder. 

Check the video

https://vimeo.com/160818169

Also note that selected vertices are also affected by dimension values, so you can move related data with the dimension.

I do not agree to call "position:" because affects dimension value.

**Comment by mirlip** [comment]
I was speaking of the text position. At the moment, both value for the dimension and text position are named "dimension:" which is confusing.
![dimension text position](https://cloud.githubusercontent.com/assets/12851284/14171604/148ab246-f734-11e5-9a0d-537d8f2ae536.PNG)

**Comment by mirlip** [comment]
Ok, found it. It's not due to an addon as it happens with factory defaults. 

1. On default scene, duplicate the cube

2. join both copies 

3. then undo with ctrl+Z.

4. Now go try to go to the material panel, it crashes blender with access violation.
