### ISSUE TITLE
Have an option to make vertecies to slide

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#9]
Hi,
It would be nice to have a vertex slide constraint for the new angle dimension. At the moment, vertecies rotate around the angle center which modifies other angles. It would be great to only modify one angle at a time. It would allow to keep the geometry clean.

**Comment by mauge123** [comment]
It agree. Maybe the current automatic plane constraint should be set to axis constraint (because you may need this behaviour) and set the plain constraint as you describe, so modified faces mantain it'

**Comment by mauge123** [comment]
Its normal in same direction.

Sorry, i give on  close icon with no intencion.

**Comment by mirlip** [comment]
C:\Users\test\git\blender\source\blender\bmesh\operators\bmo_reference.c(60): error C2220: warning treated as error - no 'object' file generated [C:\Users\test\git\build_windows_full\source\blender\bmesh\bf_bmesh.vcxproj]

**Comment by mauge123** [comment]
Could you copy the warning ? 

It should be printed before the error 

Thanks!

**Comment by mirlip** [comment]
```
c:\users\test\git\blender\source\blender\makesdna\DNA_curve_types.h(92): warning C4200: nonstandard extension used : zero-sized array in struct/union (C:\Users\test\git\blender\source\blender\depsgraph\intern\depsnode.cc) [C:\Users\test\git\build_windows_full\source\blender\depsgraph\bf_depsgraph.vcxproj]
        Cannot generate copy-ctor or copy-assignment operator when UDT contains a zero-sized array
```
I don't know why every time I log in github, it goes back to the first page and make me post the message in wrong issue thread... sorry for the chaos.

**Comment by mauge123** [comment]
Um.. i think this is not the warning that later comes to the error. At least i did not modified this line. Could you paste somewhere the full log ?

Thanks!

**Comment by mauge123** [comment]
This issue, referring to it's title can be closed, as the option has been added on a02f6abf93a7c21872ee2eca76545ab8e1706365 and modified or improved in later commits.

**Comment by mirlip** [comment]
for the compilation problem: http://www.pasteall.org/68157

**Comment by mauge123** [comment]
Um... i cannot find there the sentence pointed on first instance 

"C:\Users\test\git\blender\source\blender\bmesh\operators\bmo_reference.c(60): error C2220: warning treated as error - no 'object' file generated [C:\Users\test\git\build_windows_full\source\blender\bmesh\bf_bmesh.vcxproj]"

¿?

I see a fatal error

C:\Users\test\git\blender\source\blender\makesrna\intern\rna_modifier.c(64): fatal error C1083: Cannot open include file: 'openvdb_capi.h': No such file or directory [C:\Users\test\git\build_windows_full\source\blender\makesrna\intern\makesrna.vcxproj]

So you may check that you have the correct settings for openvdb or disable it.

**Comment by mirlip** [comment]
somehow, branches got mixed. Here is the right log:
http://www.pasteall.org/68160

**Comment by mauge123** [comment]
:P 
Should be fixed (can't test), although this is not the error pointed on first instance, and blenderplayer was linking correctly in my full config which is not the one we are usually developing on.

**Comment by mirlip** [comment]
yep works :)
just tested the new slide option, it rocks :)

**Comment by mirlip** [comment]
Hi Mauge,

The bug also appear when scaling objects in edit mode ( far away from world origin). Object mode works great.
